<template>
  <div class="loadingio-spinner-pulse-8w1csz1jkkf">
    <div class="ldio-mvobanagdp">
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>
<style scoped>
@keyframes ldio-mvobanagdp-1 {
  0% {
    top: 11.75px;
    height: 76.5px;
  }
  50% {
    top: 24.5px;
    height: 51px;
  }
  100% {
    top: 24.5px;
    height: 51px;
  }
}
@keyframes ldio-mvobanagdp-2 {
  0% {
    top: 14.9375px;
    height: 70.125px;
  }
  50% {
    top: 24.5px;
    height: 51px;
  }
  100% {
    top: 24.5px;
    height: 51px;
  }
}
@keyframes ldio-mvobanagdp-3 {
  0% {
    top: 18.125px;
    height: 63.75px;
  }
  50% {
    top: 24.5px;
    height: 51px;
  }
  100% {
    top: 24.5px;
    height: 51px;
  }
}
.ldio-mvobanagdp div {
  position: absolute;
  width: 15px;
}
.ldio-mvobanagdp div:nth-child(1) {
  left: 17.5px;
  background: #eceaea;
  animation: ldio-mvobanagdp-1 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: -0.2s;
}
.ldio-mvobanagdp div:nth-child(2) {
  left: 42.5px;
  background: #5b3a32;
  animation: ldio-mvobanagdp-2 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: -0.1s;
}
.ldio-mvobanagdp div:nth-child(3) {
  left: 67.5px;
  background: #eceaea;
  animation: ldio-mvobanagdp-3 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: undefineds;
}

.loadingio-spinner-pulse-8w1csz1jkkf {
  width: 48px;
  height: 48px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-mvobanagdp {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.48);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-mvobanagdp div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
